"""
PCB OLE Writer - Write PCB data directly to Altium PCBDoc format
Creates PCBDoc files from PCB layout data without using Altium API

Note: This is a simplified implementation. Real PCBDoc format is more complex.
For production use, consider using Altium's ASCII export/import instead.
"""
import struct
import io
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime


class PCBOLEWriter:
    """Writes PCB data to Altium-compatible format"""
    
    def __init__(self):
        pass
        
    def create_pcb_file(self, output_path: str, layout_data: Dict[str, Any]) -> bool:
        """
        Create a PCB file in Altium ASCII format (easier than OLE)
        
        Args:
            output_path: Path to output .PcbDoc file
            layout_data: PCB layout data dictionary
            
        Returns:
            True if successful, False otherwise
        """
        try:
            print(f"[PCB OLE Writer] Creating PCB file: {output_path}")
            
            # Generate ASCII PCB format (Altium can import this)
            pcb_content = self._generate_ascii_pcb(layout_data)
            
            # Write to file
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(pcb_content)
            
            print(f"[PCB OLE Writer] PCB file created successfully: {output_path}")
            return True
            
        except Exception as e:
            print(f"[PCB OLE Writer] Error creating PCB file: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def _generate_ascii_pcb(self, layout_data: Dict[str, Any]) -> str:
        """Generate Altium ASCII PCB format"""
        lines = []
        
        # Header
        lines.append("PCBDOC")
        lines.append("")
        lines.append("# Generated by EagilinsED Agent - Fully Automated PCB Builder")
        lines.append(f"# Generated: {datetime.now().isoformat()}")
        lines.append("")
        
        # Board outline
        board_size = layout_data.get('board_size', {})
        width = board_size.get('width_mm', 100.0)
        height = board_size.get('height_mm', 80.0)
        
        lines.append("[BOARD]")
        lines.append(f"Width={width}mm")
        lines.append(f"Height={height}mm")
        lines.append("LayerCount=2")
        lines.append("Layer1=Top")
        lines.append("Layer2=Bottom")
        lines.append("")
        
        # Components
        components = layout_data.get('components', [])
        if components:
            lines.append("[COMPONENTS]")
            for comp in components:
                lines.append(f"Designator={comp.get('designator', '')}")
                lines.append(f"Footprint={comp.get('footprint', '')}")
                lines.append(f"X={comp.get('x_mm', 0)}mm")
                lines.append(f"Y={comp.get('y_mm', 0)}mm")
                lines.append(f"Rotation={comp.get('rotation', 0)}")
                lines.append(f"Layer={comp.get('layer', 'Top')}")
                lines.append("")
        
        # Nets
        nets = layout_data.get('nets', [])
        if nets:
            lines.append("[NETS]")
            for net in nets:
                lines.append(f"Name={net.get('name', '')}")
                lines.append(f"IsPower={1 if net.get('is_power') else 0}")
                lines.append(f"IsGround={1 if net.get('is_ground') else 0}")
                lines.append("")
        
        # Tracks
        tracks = layout_data.get('tracks', [])
        if tracks:
            lines.append("[TRACKS]")
            for track in tracks:
                lines.append(f"Net={track.get('net', '')}")
                lines.append(f"X1={track.get('x1_mm', 0)}mm")
                lines.append(f"Y1={track.get('y1_mm', 0)}mm")
                lines.append(f"X2={track.get('x2_mm', 0)}mm")
                lines.append(f"Y2={track.get('y2_mm', 0)}mm")
                lines.append(f"Width={track.get('width_mm', 0.25)}mm")
                lines.append(f"Layer={track.get('layer', 'Top')}")
                lines.append("")
        
        # Vias
        vias = layout_data.get('vias', [])
        if vias:
            lines.append("[VIAS]")
            for via in vias:
                lines.append(f"Net={via.get('net', '')}")
                lines.append(f"X={via.get('x_mm', 0)}mm")
                lines.append(f"Y={via.get('y_mm', 0)}mm")
                lines.append(f"Diameter={via.get('diameter_mm', 0.8)}mm")
                lines.append(f"Hole={via.get('hole_mm', 0.4)}mm")
                lines.append("")
        
        # Pads
        pads = layout_data.get('pads', [])
        if pads:
            lines.append("[PADS]")
            for pad in pads:
                lines.append(f"Component={pad.get('component', '')}")
                lines.append(f"Pin={pad.get('pin', '')}")
                lines.append(f"Net={pad.get('net', '')}")
                lines.append(f"X={pad.get('x_mm', 0)}mm")
                lines.append(f"Y={pad.get('y_mm', 0)}mm")
                lines.append(f"Diameter={pad.get('diameter_mm', 1.5)}mm")
                lines.append(f"Hole={pad.get('hole_mm', 0)}mm")
                lines.append(f"Layer={pad.get('layer', 'Top')}")
                lines.append("")
        
        # Statistics
        stats = layout_data.get('statistics', {})
        lines.append("[STATISTICS]")
        lines.append(f"ComponentCount={stats.get('component_count', 0)}")
        lines.append(f"NetCount={stats.get('net_count', 0)}")
        lines.append(f"TrackCount={stats.get('track_count', 0)}")
        lines.append(f"ViaCount={stats.get('via_count', 0)}")
        lines.append(f"PadCount={stats.get('pad_count', 0)}")
        lines.append("")
        
        lines.append("# End of PCB file")
        
        return '\n'.join(lines)


def write_pcb_ole_file(layout_json_path: str, output_pcb_path: str) -> bool:
    """
    Write PCB layout to Altium-compatible file
    
    Args:
        layout_json_path: Path to PCB layout JSON
        output_pcb_path: Path to output .PcbDoc file
        
    Returns:
        True if successful, False otherwise
    """
    try:
        import json
        
        # Load layout data
        with open(layout_json_path, 'r', encoding='utf-8') as f:
            layout_data = json.load(f)
        
        # Create writer and write file
        writer = PCBOLEWriter()
        return writer.create_pcb_file(output_pcb_path, layout_data)
        
    except Exception as e:
        print(f"[PCB OLE Writer] Error: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == '__main__':
    import sys
    
    if len(sys.argv) > 2:
        layout_json = sys.argv[1]
        output_pcb = sys.argv[2]
        
        if write_pcb_ole_file(layout_json, output_pcb):
            print(f"\n✅ PCB file created: {output_pcb}")
        else:
            print("\n❌ Failed to create PCB file")
            sys.exit(1)
    else:
        print("Usage: python pcb_ole_writer.py <layout.json> <output.PcbDoc>")

